testlm2 <- lm(data = listings, price~bedrooms)
sumary(testlm2)
summary(testlm2)
testlm2 <- lm(data = listings, price~bedrooms+bathrooms)
summary(testlm2)
View(listings)
testlm2 <- lm(data = listings, price~bedrooms+bathrooms+review_scores_rating)
summary(testlm2)
testlm2 <- lm(data = listings, price~bedrooms+bathrooms+review_scores_rating+Amenities_TV)
summary(testlm2)
testlm2 <- lm(data = subset(listings, listings$price>0), log(price)~bedrooms+bathrooms+review_scores_rating+Amenities_TV)
summary(testlm2)
plot(testlm2$model$`log(price)`, testlm2$fitted.values)
plot(testlm2)
